name: "Generate Tampermonkey script"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  gomplate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install gomplate
        run: |
          wget -O gomplate https://github.com/hairyhenderson/gomplate/releases/download/v3.10.0/gomplate_linux-amd64
          chmod +x gomplate
          sudo mv gomplate /usr/local/bin/

      - name: Run gomplate
        run: gomplate < script.js.tmpl > script.js

      - uses: stefanzweifel/git-auto-commit-action@v5
